# Generated by Django 5.2.x on 2026-01-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_casedocument_file_max_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casedocument",
            name="file",
            field=models.FileField(max_length=1024, upload_to="core.models.case_document_upload_to"),
        ),
    ]
