# Generated by Django 5.2.6 on 2026-03-11 07:13

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_casedocument_file_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='property_title_type',
            field=models.CharField(blank=True, choices=[('titled', 'Titled Property'), ('untitled', 'Untitled Property')], default='', help_text='Required only for Land First Time and Transfer of Ownership cases.', max_length=20),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('not_received', 'Not Received'), ('received', 'Received'), ('in_review', 'In Review'), ('for_approval', 'For Approval'), ('approved', 'Approved'), ('for_numbering', 'For Numbering'), ('for_release', 'For Release'), ('released', 'Released'), ('returned', 'Returned for Correction'), ('withdrawn', 'Withdrawn')], default='not_received', max_length=20),
        ),
        migrations.AlterField(
            model_name='casedocument',
            name='file',
            field=models.FileField(max_length=1024, upload_to=core.models.case_document_upload_to),
        ),
    ]
