# Generated by Django 5.2.6 on 2026-03-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_case_property_title_type_alter_case_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='client_correction_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('not_received', 'Not Received'), ('received', 'Received'), ('in_review', 'In Review'), ('for_approval', 'For Approval'), ('approved', 'Approved'), ('for_numbering', 'For Numbering'), ('for_release', 'For Release'), ('released', 'Released'), ('client_correction', 'Client Correction (30 days)'), ('returned', 'Returned for Correction'), ('withdrawn', 'Withdrawn')], default='not_received', max_length=20),
        ),
    ]
