# Generated by Django 5.2.6 on 2026-03-11 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_case_client_correction_deadline_alter_case_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('not_received', 'Not Received'), ('received', 'Received'), ('in_review', 'In Review'), ('for_approval', 'For Approval'), ('approved', 'Approved'), ('for_numbering', 'For Numbering'), ('for_release', 'For Release'), ('released', 'Released'), ('client_correction', 'Client Correction (30 days)'), ('returned', 'Returned (Legacy)'), ('withdrawn', 'Withdrawn')], default='not_received', max_length=20),
        ),
    ]
