# Generated by Django 5.2.6 on 2026-03-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_case_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='lgu_municipalities',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
