# Generated by Django 5.2.6 on 2026-03-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_customuser_lgu_municipalities'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='lgu_area_code',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
    ]
