# Generated by Django 5.2.6 on 2026-03-11 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_case_lgu_area_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveIntegerField(unique=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numbers', to='core.case')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['number'],
                'indexes': [models.Index(fields=['number'], name='core_casenu_number_e586f9_idx'), models.Index(fields=['case'], name='core_casenu_case_id_12445f_idx')],
            },
        ),
    ]
