# Generated by GPT-5.2 on 2026-03-11

from django.db import migrations


def forwards(apps, schema_editor):
    Case = apps.get_model("core", "Case")
    CaseNumber = apps.get_model("core", "CaseNumber")

    # Backfill numeric legacy values from Case.numbering_number -> CaseNumber.number
    for case in Case.objects.all().only("id", "numbering_number"):
        raw = getattr(case, "numbering_number", None)
        if raw is None:
            continue
        s = str(raw).strip()
        if not s or not s.isdigit():
            continue
        n = int(s)
        if n <= 0:
            continue
        CaseNumber.objects.get_or_create(case_id=case.id, number=n)


def backwards(apps, schema_editor):
    # No reliable way to restore the old CharField values (they may have been
    # non-numeric or multiple numbers), so we leave it as a no-op.
    return


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0026_remove_case_numbering_number_casenumber"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
        migrations.RemoveField(model_name="case", name="numbering_number"),
    ]

