# Generated by Django 5.2.6 on 2026-03-11 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_backfill_casenumber_and_remove_legacy_numbering'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            UPDATE core_customuser
            SET lgu_municipality = (
                CASE
                    WHEN (lgu_municipality IS NULL OR lgu_municipality = '')
                    THEN COALESCE((lgu_municipalities->>0), '')
                    ELSE lgu_municipality
                END
            )
            WHERE 1=1
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='lgu_municipalities',
        ),
    ]
