# Generated by Django 5.2.6 on 2026-03-13 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_customuser_lgu_municipalities'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_password_change_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='password_change_count_this_month',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='password_reset_code',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
        migrations.AddField(
            model_name='customuser',
            name='password_reset_code_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('not_received', 'Not Received'), ('received', 'Received'), ('for_review', 'For Review'), ('under_review', 'Under Review'), ('for_approval', 'For Approval'), ('approved', 'Approved'), ('for_numbering', 'For Numbering'), ('for_release', 'For Release'), ('released', 'Released'), ('client_correction', 'Client Correction (30 days)'), ('returned', 'Returned (Legacy)'), ('withdrawn', 'Withdrawn')], default='not_received', max_length=20),
        ),
    ]
