# Generated by Django 5.2.6 on 2026-03-13 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_customuser_last_password_change_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='area',
            field=models.CharField(blank=True, choices=[('Alcantara', 'Alcantara'), ('Alcoy', 'Alcoy'), ('Alegria', 'Alegria'), ('Aloguinsan', 'Aloguinsan'), ('Argao', 'Argao'), ('Asturias', 'Asturias'), ('Badian', 'Badian'), ('Balamban', 'Balamban'), ('Bantayan', 'Bantayan'), ('Barili', 'Barili'), ('Boljoon', 'Boljoon'), ('Borbon', 'Borbon'), ('Carmen', 'Carmen'), ('Catmon', 'Catmon'), ('Compostela', 'Compostela'), ('Consolacion', 'Consolacion'), ('Cordova', 'Cordova'), ('Daanbantayan', 'Daanbantayan'), ('Dalaguete', 'Dalaguete'), ('Dumanjug', 'Dumanjug'), ('Ginatilan', 'Ginatilan'), ('Liloan', 'Liloan'), ('Madridejos', 'Madridejos'), ('Malabuyoc', 'Malabuyoc'), ('Medellin', 'Medellin'), ('Minglanilla', 'Minglanilla'), ('Moalboal', 'Moalboal'), ('Oslob', 'Oslob'), ('Pilar (Camotes)', 'Pilar (Camotes)'), ('Pinamungajan', 'Pinamungajan'), ('Poro (Camotes)', 'Poro (Camotes)'), ('Ronda', 'Ronda'), ('Samboan', 'Samboan'), ('San Fernando', 'San Fernando'), ('San Francisco (Camotes)', 'San Francisco (Camotes)'), ('San Remigio', 'San Remigio'), ('Santa Fe (Bantayan Island)', 'Santa Fe (Bantayan Island)'), ('Santander', 'Santander'), ('Sibonga', 'Sibonga'), ('Sogod', 'Sogod'), ('Tabogon', 'Tabogon'), ('Tabuelan', 'Tabuelan'), ('Tuburan', 'Tuburan'), ('Tudela (Camotes)', 'Tudela (Camotes)')], default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('lgu_admin', 'LGU Admin'), ('capitol_receiving', 'Receiver'), ('capitol_examiner', 'Examiner'), ('capitol_approver', 'Approver'), ('capitol_numberer', 'Numberer'), ('capitol_releaser', 'Releaser')], max_length=50),
        ),
    ]
