# Generated by Django 5.2.6 on 2026-03-14 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_case_area_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='client_contact',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='case',
            name='client_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
