# Generated by Django 5.2.6 on 2026-03-19 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_accidental_case_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='casedocument',
            name='review_remark',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='casedocument',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casedocument',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_case_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='casedocument',
            name='reviewed_ok',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'User Login'), ('login_failed', 'User Login Failed'), ('logout', 'User Logout'), ('create_user', 'Create User Account'), ('update_user', 'Update User Account'), ('deactivate_user', 'Deactivate User'), ('reactivate_user', 'Reactivate User'), ('reset_password', 'Reset Password'), ('activation_email_sent', 'Activation Email Sent'), ('activate_account', 'Account Activated'), ('password_reset_request', 'Password Reset Requested'), ('password_reset_complete', 'Password Reset Completed'), ('case_create', 'Case Created'), ('case_update', 'Case Updated'), ('case_document_review', 'Case Document Reviewed'), ('case_remark', 'Case Remark Added'), ('case_status_change', 'Case Status Changed'), ('case_receipt', 'Case Physically Received'), ('case_assignment', 'Case Assigned'), ('case_approval', 'Case Approved'), ('case_rejection', 'Case Rejected'), ('case_release', 'Case Released'), ('support_feedback', 'Support Feedback Submitted')], max_length=50),
        ),
    ]
