# Generated by Django 5.2.6 on 2026-04-18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from typing import ClassVar


def _pad_casenumbers(apps, schema_editor):
    CaseNumber = apps.get_model("core", "CaseNumber")
    for row in CaseNumber.objects.all().only("id", "number"):
        raw = str(getattr(row, "number", "") or "").strip()
        if raw.isdigit():
            row.number = raw.zfill(5)
            row.save(update_fields=["number"])


class Migration(migrations.Migration):
    dependencies: ClassVar[list[tuple[str, str]]] = [
        ("core", "0033_casedocument_review_remark_casedocument_reviewed_at_and_more"),
    ]

    operations: ClassVar[list] = [
        migrations.AddField(
            model_name="case",
            name="needs_taxmapping",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="case",
            name="taxmapped_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="taxmapper_assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="taxmapped_cases",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="casenumber",
            name="number",
            field=models.CharField(default="", max_length=5, unique=True),
        ),
        migrations.RunPython(_pad_casenumbers, reverse_code=migrations.RunPython.noop),
    ]

