"""
Django settings for legaltrack project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import importlib
import sys
from typing import Mapping, cast
from urllib.parse import parse_qsl, urlparse
from pathlib import Path
import uuid
import socket
import tempfile

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

DOTENV_PATH = BASE_DIR / ".env"


def _parse_dotenv_file(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    try:
        raw = path.read_text(encoding="utf-8")
    except OSError:
        return values

    for line in raw.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if "=" not in stripped:
            continue
        key, value = stripped.split("=", 1)
        key = key.strip()
        value = value.strip()
        if not key:
            continue
        if (value.startswith('"') and value.endswith('"')) or (value.startswith("'") and value.endswith("'")):
            value = value[1:-1]
        values[key] = value
    return values


def _load_dotenv_fallback(path: Path, *, override: bool = False) -> None:
    for key, value in _parse_dotenv_file(path).items():
        if override or key not in os.environ:
            os.environ[key] = value


_dotenv_values: object | None = None
_load_dotenv: object | None = None
try:
    _dotenv = importlib.import_module("dotenv")
    _dotenv_values = getattr(_dotenv, "dotenv_values", None)
    _load_dotenv = getattr(_dotenv, "load_dotenv", None)
except Exception:
    _dotenv_values = None
    _load_dotenv = None

DOTENV_VALUES: dict[str, str] = {}
if DOTENV_PATH.exists():
    # In development, prefer `.env` values. This still allows easy toggling
    # between sqlite/supabase by editing `.env`.
    if callable(_dotenv_values):
        raw_values = cast(Mapping[str, str | None], _dotenv_values(str(DOTENV_PATH)))
        DOTENV_VALUES = {k: v for k, v in raw_values.items() if k and v is not None}
    else:
        DOTENV_VALUES = _parse_dotenv_file(DOTENV_PATH)

    if callable(_load_dotenv):
        try:
            _load_dotenv(DOTENV_PATH, override=True)
        except TypeError:
            _load_dotenv(DOTENV_PATH)
    else:
        _load_dotenv_fallback(DOTENV_PATH, override=True)


def _env(key: str, default: str | None = None) -> str | None:
    val = DOTENV_VALUES.get(key)
    if val is not None and str(val).strip() != "":
        return str(val)
    return os.getenv(key) or default


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Support multiple env var names to avoid deploy-time mismatches across hosts.
_secret_from_env = (
    _env("DJANGO_SECRET_KEY")
    or _env("DJANGO_SECRET")
    or _env("SECRET_KEY")
)
SECRET_KEY = _secret_from_env or uuid.uuid4().hex

# SECURITY WARNING: don't run with debug turned on in production!
def _truthy(value: str | None) -> bool:
    return str(value or "").strip().lower() in {"1", "true", "yes", "y", "on"}


def _is_vercel() -> bool:
    # Vercel sets VERCEL=1 and VERCEL_ENV=production|preview|development
    return _truthy(os.environ.get("VERCEL")) or bool(os.environ.get("VERCEL_ENV"))


# Default DEBUG:
# - local dev: True when a .env file is present
# - production (Vercel): False
DEBUG = _truthy(_env("DJANGO_DEBUG") or ("true" if DOTENV_PATH.exists() else "false"))

# In production/serverless environments, a random SECRET_KEY per cold start will
# break logins (sessions/CSRF) across instances. Require an env-provided key.
if not DEBUG and not _secret_from_env:
    raise ImproperlyConfigured(
        "DJANGO_SECRET_KEY must be set when DJANGO_DEBUG=false (production)."
    )


def _split_csv(value: str | None) -> list[str]:
    if not value:
        return []
    return [item.strip() for item in value.split(",") if item.strip()]


_default_hosts = ["localhost", "127.0.0.1", ".vercel.app", ".onrender.com"]
ALLOWED_HOSTS = _split_csv(_env("DJANGO_ALLOWED_HOSTS")) or _default_hosts

# Required on Vercel (proxy terminates TLS).
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True
    # Allow Vercel/Render preview/prod domains by default.
    CSRF_TRUSTED_ORIGINS = _split_csv(_env("DJANGO_CSRF_TRUSTED_ORIGINS")) or [
        "https://*.vercel.app",
        "https://*.onrender.com",
    ]


# Application definition

INSTALLED_APPS = [
    'whitenoise.runserver_nostatic',
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "core",
    "rest_framework",
    # 'password_reset',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    'whitenoise.middleware.WhiteNoiseMiddleware',
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "core.middleware.SessionTimeoutMiddleware",
    "core.middleware.ForcePasswordChangeMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# Cross-origin frontend support (e.g., Vercel frontend -> self-hosted backend)
# Enable by setting:
# - DJANGO_CORS_ALLOWED_ORIGINS=https://your-app.vercel.app
# - DJANGO_CSRF_TRUSTED_ORIGINS=https://your-app.vercel.app,https://your-backend-domain
# - LEGALTRACK_CROSS_SITE_COOKIES=true
try:
    import corsheaders  # type: ignore  # noqa: F401
    _has_corsheaders = True
except Exception:
    _has_corsheaders = False

if _has_corsheaders and "corsheaders" not in INSTALLED_APPS:
    INSTALLED_APPS = ["corsheaders", *INSTALLED_APPS]
    # Must be placed as high as possible, especially before CommonMiddleware
    if "corsheaders.middleware.CorsMiddleware" not in MIDDLEWARE:
        MIDDLEWARE = [
            "corsheaders.middleware.CorsMiddleware",
            *MIDDLEWARE,
        ]

    CORS_ALLOWED_ORIGINS = _split_csv(_env("DJANGO_CORS_ALLOWED_ORIGINS"))
    CORS_ALLOW_CREDENTIALS = True

    # In cross-origin setups, cookies must be SameSite=None; Secure.
    if _truthy(_env("LEGALTRACK_CROSS_SITE_COOKIES")):
        CSRF_COOKIE_SAMESITE = "None"
        SESSION_COOKIE_SAMESITE = "None"
        CSRF_COOKIE_SECURE = True
        SESSION_COOKIE_SECURE = True

ROOT_URLCONF = "legaltrack.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "legaltrack.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Authentication
AUTHENTICATION_BACKENDS = [
    "core.backends.AdminEmailAliasBackend",
    "core.backends.StaffIdBackend",
]


def _database_from_url(database_url: str) -> dict[str, object]:
    
    parsed = urlparse(database_url)

    scheme = (parsed.scheme or "").lower()
    if scheme in {"postgres", "postgresql", "postgresql+psycopg2"}:
        engine = "django.db.backends.postgresql"
    elif scheme in {"sqlite", "sqlite3"}:
        engine = "django.db.backends.sqlite3"
    else:
        raise ValueError(
            f"Unsupported DATABASE_URL scheme '{parsed.scheme}'. Use postgres/postgresql or sqlite."
        )

    if engine == "django.db.backends.sqlite3":
        name = (parsed.path or "").lstrip("/") or "db.sqlite3"
        return {"ENGINE": engine, "NAME": str(BASE_DIR / name)}

    query = dict(parse_qsl(parsed.query, keep_blank_values=True))
    options = {}
    if "sslmode" in query:
        options["sslmode"] = query["sslmode"]

    config: dict[str, object] = {
        "ENGINE": engine,
        "NAME": (parsed.path or "").lstrip("/") or os.getenv("DB_NAME", "postgres"),
        "USER": parsed.username or os.getenv("DB_USER", "postgres"),
        "PASSWORD": parsed.password or os.getenv("DB_PASSWORD", "CHANGE_ME_PASSWORD"),
        "HOST": parsed.hostname or os.getenv("DB_HOST", "CHANGE_ME_HOST"),
        "PORT": str(parsed.port or os.getenv("DB_PORT", "5432")),
        "OPTIONS": options,
    }

    # Vercel outbound networking can fail when the DB hostname resolves to IPv6
    # first. Supabase hosts typically have both A and AAAA records; psycopg2 may
    # pick IPv6 and error with "Cannot assign requested address".
    #
    # Force IPv4 resolution for serverless platforms (Vercel, Render, AWS Lambda).
    # These platforms may have IPv6 routing issues with Supabase.
    # sslmode=require does not verify hostnames, so this is safe.
    #
    # Detection strategy:
    # - Vercel: VERCEL or VERCEL_ENV
    # - Render: Check for /etc/hostname containing "render" or check common Render env vars
    # - AWS Lambda: AWS_LAMBDA_FUNCTION_NAME
    # - Railway: RAILWAY_ENVIRONMENT
    # - Fallback: if not DEBUG (production), assume serverless
    is_serverless = (
        _truthy(os.environ.get("VERCEL"))
        or bool(os.environ.get("VERCEL_ENV"))
        or bool(os.environ.get("AWS_LAMBDA_FUNCTION_NAME"))
        or bool(os.environ.get("RAILWAY_ENVIRONMENT"))
        or bool(os.environ.get("RENDER_SERVICE_NAME"))  # Render service identifier
        or bool(os.environ.get("RENDER"))  # Generic Render flag
        or (not DEBUG and not DOTENV_PATH.exists())  # Production without .env
    )
    
    if is_serverless:
        try:
            host_val = config.get("HOST")
            host = str(host_val or "").strip()
            
            # Only resolve if it looks like a hostname (not already an IP)
            if host and "." in host and not all(c.isdigit() or c == "." for c in host):
                try:
                    # Use getaddrinfo with explicit AF_INET for IPv4-only resolution
                    # This is more reliable than gethostbyname() on serverless platforms
                    addr_infos = socket.getaddrinfo(
                        host, 
                        int(str(config.get("PORT") or 5432)),
                        family=socket.AF_INET,  # Force IPv4
                        type=socket.SOCK_STREAM
                    )
                    if addr_infos:
                        ipv4_addr = addr_infos[0][4][0]  # Extract IP from first result
                        if ipv4_addr and ":" not in ipv4_addr:  # Ensure it's IPv4, not IPv6
                            config["HOST"] = ipv4_addr
                            print(
                                f"[INFO] Serverless mode: Resolved {host} -> {ipv4_addr}",
                                file=sys.stderr,
                            )
                except (socket.gaierror, socket.error, IndexError, OSError, ValueError) as e:
                    print(
                        f"[WARN] IPv4 resolution failed for {host}: {type(e).__name__}: {e}",
                        file=sys.stderr,
                    )
                    # Fallback: keep original hostname, psycopg2 will attempt resolution
        except Exception as e:
            print(
                f"[ERROR] Unexpected error in IPv4 resolution: {type(e).__name__}: {e}",
                file=sys.stderr,
            )

    return config


LEGALTRACK_DB_PROVIDER = (_env("LEGALTRACK_DB_PROVIDER", "supabase") or "supabase").strip().lower()

# Keep automated tests hermetic and non-interactive.
if any(arg == "test" or arg.endswith("manage.py test") for arg in sys.argv):
    LEGALTRACK_DB_PROVIDER = "sqlite"

if LEGALTRACK_DB_PROVIDER not in {"supabase", "sqlite"}:
    raise ImproperlyConfigured(
        "LEGALTRACK_DB_PROVIDER must be 'supabase' or 'sqlite'."
    )

if LEGALTRACK_DB_PROVIDER == "supabase":
    database_url = (_env("DATABASE_URL") or "").strip()
    if not database_url:
        # Don't silently fall back in production: that makes the app "work" but
        # nothing persists (login/tracking will fail). Allow fallback only when
        # explicitly enabled for demo/debug purposes.
        if _is_vercel() and _truthy(_env("LEGALTRACK_ENABLE_VERCEL_SQLITE_FALLBACK")):
            LEGALTRACK_DB_PROVIDER = "sqlite"
        else:
            raise ImproperlyConfigured(
                "DATABASE_URL is required when LEGALTRACK_DB_PROVIDER=supabase."
            )
    # Optional resiliency for local dev: if the configured DB host cannot be
    # resolved from this machine, you may opt-in to falling back to local
    # SQLite so commands like `manage.py migrate` / `runserver` remain usable.
    #
    # IMPORTANT: This fallback is intentionally *disabled by default* so you
    # don't accidentally think you're using Supabase while actually using
    # local SQLite.
    LEGALTRACK_ALLOW_SQLITE_FALLBACK = _truthy(_env("LEGALTRACK_ALLOW_SQLITE_FALLBACK"))
    try:
        parsed = urlparse(database_url)
        hostname = parsed.hostname
    except Exception:
        hostname = None

    if hostname:
        try:
            # Attempt to resolve either A or AAAA records. If resolution
            # fails (socket.gaierror), assume host is unreachable from
            # this environment and fallback to sqlite.
            socket.getaddrinfo(hostname, None)
        except Exception:
            if LEGALTRACK_ALLOW_SQLITE_FALLBACK and DEBUG:
                import warnings

                warnings.warn(
                    f"Database host '{hostname}' is not resolvable from this machine; "
                    "falling back to local SQLite for development.",
                    RuntimeWarning,
                )
                LEGALTRACK_DB_PROVIDER = "sqlite"
            else:
                raise ImproperlyConfigured(
                    f"Database host '{hostname}' is not resolvable from this machine. "
                    "Fix your DNS/network or update DATABASE_URL. "
                    "(To allow local SQLite fallback in dev, set LEGALTRACK_ALLOW_SQLITE_FALLBACK=true.)"
                )

    # Re-check provider in case we fell back
    if LEGALTRACK_DB_PROVIDER != "supabase":
        sqlite_name = ":memory:" if ("test" in sys.argv) else (BASE_DIR / "db.sqlite3")
        if _is_vercel() and sqlite_name != ":memory:":
            sqlite_name = Path(tempfile.gettempdir()) / "legaltrack.sqlite3"
        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.sqlite3",
                "NAME": sqlite_name,
            }
        }
    else:
        DATABASES = {"default": _database_from_url(database_url)}
    
else:
    # SQLite is still allowed explicitly (useful for tests/offline dev).
    sqlite_name = ":memory:" if ("test" in sys.argv) else (BASE_DIR / "db.sqlite3")
    if _is_vercel() and sqlite_name != ":memory:":
        sqlite_name = Path(tempfile.gettempdir()) / "legaltrack.sqlite3"
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": sqlite_name,
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_USER_MODEL = "core.CustomUser"

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {"min_length": 12},
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
    {
        "NAME": "core.validators.StrongPasswordComplexityValidator",
    },
]

# Security (Module 1): prefer Argon2 password hashing
PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.Argon2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
]

# Module 1: password reset tokens should expire within 24 hours
PASSWORD_RESET_TIMEOUT = 60 * 60 * 24

# Email
# Dev default prints emails to the console. When Brevo SMTP is configured via env,
# switch to SMTP automatically.
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "no-reply@cebu.gov.ph")

# Email Configuration
EMAIL_HOST = os.environ.get("EMAIL_HOST", "smtp.gmail.com").strip()
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587") or "587")
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "").strip()
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "").strip()
EMAIL_USE_TLS = (os.environ.get("EMAIL_USE_TLS", "1").strip() not in {"0", "false", "False"})
EMAIL_USE_SSL = False
EMAIL_TIMEOUT = 10

if EMAIL_HOST_USER and EMAIL_HOST_PASSWORD:
    # Use standard SMTP backend for production (Vercel), custom for Windows dev
    if _is_vercel():
        EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    else:
        EMAIL_BACKEND = "core.email_backends.GmailEmailBackend"
else:
    # Fallback to console for development
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

# Local/dev convenience toggles.
# - `LEGALTRACK_SEND_EMAILS`: keep emails enabled (console backend in dev).
# - `LEGALTRACK_SHOW_ACTIVATION_LINK`: show activation link on-screen (dev only).
LEGALTRACK_SEND_EMAILS = (os.environ.get("LEGALTRACK_SEND_EMAILS", "1").strip() not in {"0", "false", "False"})
LEGALTRACK_SHOW_ACTIVATION_LINK = (os.environ.get("LEGALTRACK_SHOW_ACTIVATION_LINK", "1").strip() not in {"0", "false", "False"})

# Optional case notifications.
LEGALTRACK_SEND_CASE_EMAILS = (os.environ.get("LEGALTRACK_SEND_CASE_EMAILS", "1").strip() not in {"0", "false", "False"})

# SNS stub (provider integration not configured yet).
LEGALTRACK_SNS_ENABLED = (os.environ.get("LEGALTRACK_SNS_ENABLED", "0").strip() not in {"0", "false", "False"})

# Textbelt (SMS) configuration
TEXTBELT_API_KEY = os.environ.get("TEXTBELT_API_KEY", "").strip()
TEXTBELT_REGION = os.environ.get("TEXTBELT_REGION", "").strip()  # optional

# Security: Django recommends POST for logout. Allowing GET is convenient during local dev,
# but should be disabled in production.
LEGALTRACK_ALLOW_GET_LOGOUT = DEBUG


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"
TIME_ZONE = "Asia/Manila"
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Existing static URL plus deploy prep
STATIC_URL = "/static/"

STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"
# Vercel serverless builds may not run `collectstatic`. Manifest storage will crash
# if the manifest is missing, so prefer a non-manifest storage there.
STATICFILES_STORAGE = (
    "whitenoise.storage.CompressedStaticFilesStorage"
    if _is_vercel()
    else "whitenoise.storage.CompressedManifestStaticFilesStorage"
)


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGIN_REDIRECT_URL = "dashboard"
LOGOUT_REDIRECT_URL = "login"


# MEDIA
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")
